### ISSUE TITLE
todo 

### ISSUE THREAD

**Issue by suuuuu017** [suuuuu017/PL4WAProj#1]
profile page

- [ ] profile photo 
- [x] active post/past post (R)
- [x] edit/delete post on profile page (R)
- [x] sort based on date
- [x] update the image in the cards
- [x] joined post
-----------------------------------------
- [ ] hashpassword
- [ ] social media 

main page

- [x] photo for post (S)
- [ ] comment section (S)
- [x] fix repeat joining on post (S)
- [x] search (S)
- [x] make alert go away
- [x] fix displaying
- [x] fix refreshing then double sumbit (dont know how to fix)
- [x] fix spaces
- [x] fix search pics
maybe features

- [ ] chatbox
